/**
 * Copies the shared modules the browser needs into web/shared/vendor/.
 *
 * The portals are plain ES modules with no bundler, so formatting and brand
 * tokens are copied rather than imported across the tree. Copying keeps one
 * source of truth: nobody edits the vendor copies, and `npm run dev` refreshes
 * them before the Worker starts.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'web', 'shared', 'vendor');
await mkdir(OUT, { recursive: true });

const FILES = ['src/core/format.js', 'src/core/brand.js'];
const BANNER = '/* GENERATED by scripts/build-web.mjs — edit the source under src/core/, not this copy. */\n';

for (const rel of FILES) {
  const body = await readFile(path.join(ROOT, rel), 'utf8');
  const out = path.join(OUT, path.basename(rel));
  await writeFile(out, BANNER + body);
  console.log(`  ${rel} → web/shared/vendor/${path.basename(rel)}`);
}
